import os
import asyncio
import logging
from typing import Optional

from sqlalchemy import create_engine, Column, Integer, Text, Engine
from sqlalchemy.orm import declarative_base, sessionmaker, Session

logger = logging.getLogger(__name__)

Base = declarative_base()

class ChatRecord(Base):
    """SQLAlchemy ORM Model representing a single chat exchange."""
    __tablename__ = 'chat_records'
    id = Column(Integer, primary_key=True)
    user_message = Column(Text, nullable=False)
    bot_reply = Column(Text, nullable=False)

# Guardrail: Initialize engine lazily to ensure environment is fully loaded First
_engine: Optional[Engine] = None
_SessionLocal: Optional[sessionmaker] = None

def init_db() -> Engine:
    """
    Initializes the database engine and the session registry. 
    Implements robust connection pooling if connected to a real database URI.
    
    Returns:
        Engine: The initialized SQLAlchemy database engine.
    """
    global _engine, _SessionLocal
    if _engine is not None:
        return _engine
        
    db_url = os.environ.get("DB_URL")
    if not db_url:
        logger.warning("DB_URL not found, falling back to SQLite for local development.")
        db_url = "sqlite:///./local_chat.db"
        # SQLite memory/file engines don't support explicit pooling parameters easily like Postgres
        _engine = create_engine(db_url, connect_args={"check_same_thread": False})
    else:
        # Production optimization: Explicitly bound connection pools
        _engine = create_engine(
            db_url, 
            pool_size=5, 
            max_overflow=10, 
            pool_timeout=30,
            pool_recycle=1800
        )
        
    Base.metadata.create_all(bind=_engine)
    _SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=_engine)
    logger.info("Database engine and schema initialized.")
    return _engine

async def save_chat_history(user_msg: str, bot_reply: str) -> None:
    """
    Saves a chat history record to the database explicitly using a dedicated thread
    to prevent blocking the async event loop.
    
    Args:
        user_msg (str): The prompt submitted by the user.
        bot_reply (str): The response generated by the AI block.
    """
    if _SessionLocal is None:
        init_db()
        
    def _save() -> None:
        # Ensure _SessionLocal is functionally typed inside the closure
        if _SessionLocal is None:
            raise RuntimeError("Database session factory is uninitialized.")
            
        db: Session = _SessionLocal()
        try:
            record = ChatRecord(user_message=user_msg, bot_reply=bot_reply)
            db.add(record)
            db.commit()
        except Exception as e:
            logger.error(f"Failed to save chat to DB: {str(e)}")
            db.rollback()
        finally:
            db.close()

    await asyncio.to_thread(_save)
